language: node_js
node_js: 10
cache:
  npm: false
  directories:
  - "$HOME/.pnpm-store"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm i --frozen-lockfile
jobs:
  include:
  - stage: lint
    script: pnpm run lint
  - stage: test
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script: pnpm run test
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
  - stage: build
    if: tag IS blank
    script: pnpm run build
  - stage: release
    if: tag IS present
    script: pnpm run build
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_token: "$NPM_TOKEN"
      edge: true
      skip_cleanup: true
      on:
        tags: true
